# Generated by Django 5.2.8 on 2025-11-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
    ]
