# Generated by Django 5.2.8 on 2025-11-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Health Weight Record',
                'verbose_name_plural': 'Health Weight Records',
                'ordering': ['date'],
            },
        ),
    ]
