# Generated by Django 5.2.8 on 2025-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_healthweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
