# Generated by Django 5.2.8 on 2025-11-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
