# Generated by Django 5.2.8 on 2025-11-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_techstack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstack',
            options={},
        ),
    ]
