# Generated by Django 5.2.8 on 2025-11-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='novels',
            name='genere',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
